version: 2

aliases:
  - &restore-cache
    restore_cache:
      key: dependency-cache-{{ checksum "package.json" }}
  - &install-deps
    run:
      name: Install dependencies
      command: npm install --ignore-scripts
  - &build-packages
    run:
      name: Build
      command: npm run build

jobs:
  build:
    working_directory: ~/nest
    docker:
      - image: cimg/node:24.11
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install --ignore-scripts
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build

  integration_tests:
    working_directory: ~/nest
    docker:
      - image: cimg/node:24.11
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - run:
          name: Integration tests
          command: npm run test:integration

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - integration_tests:
          requires:
            - build
