/**
 * Injection tokens
 */
export const CONFIGURATION_SERVICE_TOKEN = Symbol('CONFIG_SERVICE');
export const CONFIGURATION_TOKEN = 'CONFIGURATION_TOKEN';
export const CONFIGURATION_LOADER = 'CONFIGURATION_LOADER';
export const VALIDATED_ENV_LOADER = 'VALIDATED_ENV_LOADER';

export const PARTIAL_CONFIGURATION_KEY = 'PARTIAL_CONFIGURATION_KEY';
export const PARTIAL_CONFIGURATION_PROPNAME = 'KEY';
export const VALIDATED_ENV_PROPNAME = '_PROCESS_ENV_VALIDATED';
export const AS_PROVIDER_METHOD_KEY = 'asProvider';
