/**
 * Injection tokens
 */
export const CONFIGURATION_SERVICE_TOKEN = Symbol('CONFIG_SERVICE');
export const CONFIGURATION_TOKEN = 'CONFIGURATION_TOKEN';
export const CONFIGURATION_LOADER = 'CONFIGURATION_LOADER';
export const PARTIAL_CONFIGURATION_KEY = 'PARTIAL_CONFIGURATION';
